### ISSUE TITLE
MicroPython implementation and tests

### ISSUE THREAD

**Issue by bskinn** [bskinn/stdio-mgr#96]
MicroPython types appear not to implement `.mro()`, in either the Python 2 or Python 3 forms:

```
>>> str.__bases__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'str' has no attribute '__bases__'
>>> import io
>>> io.StringIO.__bases__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'StringIO' has no attribute '__bases__'
>>> io.StringIO.__mro__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'StringIO' has no attribute '__mro__'
>>> dir(io.StringIO)
['__class__', '__enter__', '__exit__', '__name__', 'close', 'read', 'readinto', 'readline', 'write', 'flush', 'getvalue', 'seek']
```

*Is* there a way to introspect  the inheritance hierarchy in MP?

Also: Yikes, [the MRO itself is not CPython-compliant](https://docs.micropython.org/en/latest/genrst/core_language.html#method-resolution-order-mro-is-not-compliant-with-cpython).

_Adapted from originally post by @bskinn in https://github.com/bskinn/stdio-mgr/issues/81#issuecomment-531810997_

**Comment by bskinn** [comment]
MicroPython implements a significantly reduced class hierarchy in its [`io` module](https://docs.micropython.org/en/latest/library/uio.html). Presumably the `sys.stdfoo` also live on this reduced hierarchy?

**Comment by bskinn** [comment]
Might be worth just testing MP at stdio-mgr v1.0.1, modded to remove attrs.

**Comment by bskinn** [comment]
MicroPython appears to have crippled `sys`, not allowing its members to be set. Other modules are not crippled in this way:

```
>>> import io
>>> io.foo = "bar"
>>> io
<module 'io' from '/home/pydev/.micropython/lib/io.py'>
>>> dir(io)
['__class__', '__name__', 'open', '__file__', 'BytesIO', 'FileIO', 'IOBase', 'StringIO', 'TextIOWrapper', 'SEEK_SET', 'SEEK_CUR', 'SEEK_END', 'foo']
>>> import sys
>>> sys.foo = "bar"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'foo'
>>> import unittest
>>> unittest.foo = "bar"
>>> dir(unittest)
['__class__', '__name__', 'main', '__file__', 'sys', 'skip', 'foo', 'SkipTest', 'AssertRaisesContext', 'TestCase', 'skipIf', 'skipUnless', 'TestSuite', 'TestRunner', 'TestResult', 'run_class']
```

**Comment by bskinn** [comment]
Given the above, @jayvdb, I'm at a loss as to how to implement even basic stream wraps/mocks. I think MicroPython may be a nonstarter.
